# Generated by Django 6.0.5 on 2026-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plea_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plea',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес (Улица, дом)'),
        ),
        migrations.AddField(
            model_name='plea',
            name='apartment',
            field=models.CharField(default='', max_length=10, verbose_name='Квартира'),
        ),
    ]
