# Generated by Django 6.0.5 on 2026-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plea_address_plea_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес по умолчанию'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира'),
        ),
    ]
