# Generated by Django 6.0.5 on 2026-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_address_profile_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plea',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='plea',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Квартира'),
        ),
    ]
